### ISSUE TITLE
English text is not reported when it starts with `A`

### ISSUE THREAD

**Issue by stof** [dgraham/eslint-plugin-i18n-text#8]
Looking at the code, it seems to expect at least 2 letters for the first word. This means that `a.textContent = 'A word with a single letter.'` is not reported as being English text.

**Comment by dgraham** [comment]
It's a best-effort rule to prevent most but not all untranslated text from being introduced to a project or to automate building the list of hardcoded strings that still need to be translated. So it won't catch everything without a more complicated implementation.

**Comment by stof** [comment]
Maybe should the regex from `^[A-Z][a-z]+\s` to `^[A-Z][a-z]*\s` (i.e. allowing to match a single capital letter followed by space) would be OK ?

**Comment by dgraham** [comment]
I think I tried it when I was first writing this, and that matched too many false positives. You might try it in a fork of this rule and see how it goes for your project.

**Comment by stof** [comment]
On my own project, I get no false positive when using my suggested regexp. It only report one additional violation in my case, and it is an expected one (that's the one that I would have expected and because of which I reported this issue).
I'll let you decide whether you want to include it or no in an update.
